# Site settings
title: UltraDiff
email: dantarion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Automated diff's of Ultra Street Fighter 4 patches
baseurl: "/sf4tools/" # the subpath of your site, e.g. /blog/
url: "http://dantarion.github.io/" # the base hostname & protocol for your site
twitter_username: dantarion
github_username:  dantarion

# Build settings
markdown: kramdown
